name: image-build-and-push

on:
  workflow_dispatch:
    inputs:
      imageName:
        description: "Workspace image name"
        required: true
        type: string
      repoPass:
        description: "GitHub token with permissions to push to GHCR"
        required: true
        type: string
      repoUser:
        description: "GitHub username associated with the token"
        required: true
        type: string


jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
      
      
      - name: Login to GHCR (Podman)
        run: |
          PASS=${{ '${{ inputs.repoPass }}' }}
          USER=${{ '${{ inputs.repoUser }}' }}
          echo "$PASS" | podman login ghcr.io \
            -u "$USER" \
            --password-stdin

      # --- Build image with Podman ---
      - name: Podman build
        run: |
          IMAGE=${{ '${{ inputs.imageName }}' }}
          podman build -t "$IMAGE" -f Dockerfile .

      
      - name: Podman push
        run: |
          IMAGE=${{ '${{ inputs.imageName }}' }}
          podman push "$IMAGE"