name: Fetch wecollab repo

on:
  workflow_dispatch:
    inputs:
      workspaceName:
        description: "Workspace name from Backstage"
        required: true
        type: string


jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: source-repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Wipro-Organization-105/WeCollab
          ref: main
          path: destination-repo
      - name: Copy main.tf files
        run: |
          DIR="${{ '${{ inputs.workspaceName }}' }}"
          mkdir -p destination-repo/Terraform-Template/$DIR
          cp source-repo/main.tf destination-repo/Terraform-Template/$DIR/
          JSONFILE="$DIR/group-template-mapping.json"
          TEMPJSONFILE="$DIR/group-template-mapping-temp.json"
          NEWPATH="$DIR/main.tf"
          GROUP="${{ values.groupname }}"
          jq --arg group "$GROUP" --arg path "$NEWPATH" \
          '.groupTemplateMap[$group].path += [$path]' "$JSONFILE" > "$TEMPJSONFILE" \
          && mv "$TEMPJSONFILE" "$JSONFILE"
      - name: Commit and push changes
        run: |
          cd destination-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update Terraform template"
          git push origin HEAD:main